## server configuration
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

---
spring:
  config:
    activate:
      on-profile: loc
---
## active profile : dev
spring:
  config:
    activate:
      on-profile: dev
---
## active profile : prod
spring:
  config:
    activate:
      on-profile: prod
---

## logging
logging:
  config: classpath:log4j2.xml
  register-shutdown-hook: true

## active profile
spring:
  session:
    store-type: jdbc
  mustache:
    servlet:
      expose-session-attributes: true
    ## upload file size
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  main:
    allow-circular-references: true

server:
  shutdown: graceful
  servlet:
    session:
      timeout: 1800

