## server configuration PORT 및 Encoding 설정
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

## spring profile 및 database 설정
spring:
## datasource
  datasource:
    #driver-class-name: org.mariadb.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Seoul
    username: { database username }
    password: { database password }

## logging configuration
logging:
  config: classpath:log4j2.xml

## mybatis configuration
mybatis:
  ## configuration mybatis 설정 파일로 xml을 사용할 경우.
  #config-location: classpath:mybatis/mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true
  ## Mapper Location
  mapper-locations: classpath:mybatis/mappers/*Mapper.xml
  ## Model package aliases
  type-aliases-package: com.template.springmybatis.demo.controller.model

