CREATE TABLE `weekly_comment` (
  `WEEKLY_SEQ` int(11) NOT NULL AUTO_INCREMENT COMMENT '고유 번호',
  `WEEKLY_CATEGORY_SEQ` int(11) NOT NULL COMMENT '주간논평 카테고리 코드',
  `WEEKLY_TITLE` varchar(150) NOT NULL COMMENT '제목',
  `WEEKLY_SUBTITLE` varchar(150) DEFAULT NULL COMMENT '부제목',
  `WEEKLY_AUTHOR` int(11) DEFAULT NULL COMMENT '저자 고유번호',
  `WEEKLY_CONTENT` text DEFAULT NULL COMMENT '내용',
  `WEEKLY_THUMGNAIL_IMAGE` varchar(300) DEFAULT NULL COMMENT '섬네일 이미지 주소',
  `APPEND_DATE` DATETIME DEFAULT current_timestamp() COMMENT '등록일',
  `UPDATE_DATE` DATETIME DEFAULT current_timestamp() COMMENT '수정일',
  `START_DATE` DATETIME DEFAULT current_timestamp COMMENT '게시 시작일',
  `END_DATE` DATETIME DEFAULT (current_timestamp() + INTERVAL 999 YEAR)  COMMENT '게시 종료일',
  `APPEND_USER` int(11) DEFAULT NULL COMMENT '등록자',
  `UPDATE_USER` int(11) DEFAULT NULL COMMENT '수정자',
  `VIEW_COUNT` int(11) DEFAULT 0 COMMENT '조회수',
  `USE_YN` tinyint(4) DEFAULT NULL COMMENT '사용 여부',
  PRIMARY KEY (`WEEKLY_SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='주간논평';

CREATE TABLE `WEEKLY_COMMENT_CATEGORY` (
	`WEEKLY_CATEGORY_SEQ`	INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '고유 번호', 
	`WEEKLY_CATEGORY_VALUE`	VARCHAR(50) NOT NULL COMMENT '주간논평 카테고리 값'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='주간논평 카테고리';